# Minimal Jekyll config
title: Jade Novels

# GitHub Pages settings
baseurl: "/jadenovels"
url: "https://ancientjadestatue.github.io"

# Development settings
livereload: true
host: 0.0.0.0
port: 4000

# Build settings
incremental: true
show_drafts: true
