title: Jade's Romance Library
description: A collection of contemporary romance novels
baseurl: ""  # Leave empty for GitHub Pages unless using a custom domain
url: ""  # GitHub Pages will set this automatically

# Build settings
markdown: kramdown
highlighter: rouge
# Removed theme: minima since we're using custom layouts

# Collections
collections:
  books:
    output: true
    permalink: /books/:name/
  chapters:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
